<style>

    .col-center-block {
        float: none;
        display: block;
        margin-left: auto;
        margin-right: auto;
        float: none !important;
        margin-bottom: 200px;
    }
    label{
        width: 100%;
    }
</style>


    <div class="col-lg-6 col-center-block" >
        <div class="panel-primary panel">

            <div class="panel-heading">Alterar Dados de Acesso</div>
            <?php echo $this->form()->openTag($form); ?>
            <div class="panel-body">
                <?php if( $this->flashMessenger()->hasMessages('error') ): ?>
                    <?php  echo $this->flashMessenger()->render('error', array('alert', 'alert-dismissible', 'alert-danger')); ?>
                <?php endif; ?>
                <?php if( $this->flashMessenger()->hasMessages('success') ): ?>
                    <?php  echo $this->flashMessenger()->render('success', array('alert', 'alert-dismissible', 'alert-success')); ?>
                <?php endif; ?>

                    <div class="form-group" style="width: 100%;">
                        <?php echo $this->formRow($form->get('senha_atual')); ?>
                    </div>



                    <div class="form-group">
                        <?php echo $this->formRow($form->get('nova_senha')); ?>
                    </div>


                    <div class="form-group">
                        <?php echo $this->formRow($form->get('confirmar_nova_senha')); ?>
                    </div>


            </div>
            <div class="panel-footer">
                <?php echo $this->formRow($form->get('alterar')); ?>
            </div>
            <?php echo $this->form()->closeTag($form); ?>
        </div>
    </div>
