<style>
    .radioBotao{

        height: 20px;
        width: 20px;
        display: inline;
    }
    .form-group fieldset label{
        margin-right: 80px !important;
        margin-left: 15px;
    }
    .form-group fieldset{

    }
    .form-group legend{
        font-size: 15px;
        margin-left: 15px;
        /*border-bottom: none;*/
        margin-bottom: 2px;
        font-weight: bold;
    }
    .col-center-block {
        float: none;
        display: block;
        margin-left: auto;
        margin-right: auto;
        float: none !important;
    }
</style>

<?php echo $this->doctype(); ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        ->prependStylesheet($this->basePath('css/style.css'))
        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
        ->prependStylesheet($this->basePath('css/bootstrap.min.css')) ?>

    <!-- Scripts -->
    <?php echo $this->headScript()
        ->prependFile($this->basePath('js/bootstrap.min.js'))
        ->prependFile($this->basePath('js/jquery.min.js'))
        ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
        ->prependFile($this->basePath('js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
    ; ?>

</head>
<body>

<div class="container">

        <div class="col-lg-6 col-center-block" style="margin-top: 100px;">
            <div class="panel-primary panel">

                <div class="panel-heading">Auntenticacao no sistema</div>
                <?php echo $this->form()->openTag($form); ?>
                <div class="panel-body">
                    <?php if( $this->flashMessenger()->hasMessages('error') ): ?>
                        <?php  echo $this->flashMessenger()->render('error', array('alert', 'alert-dismissible', 'alert-danger')); ?>
                    <?php endif; ?>
                    <div class="col-lg-12 row" >
                        <div class="form-group">
                            <?php echo $this->formRow($form->get('login')); ?>
                        </div>
                    </div>

                    <div class="col-lg-12 row" >
                        <div class="form-group">
                            <?php echo $this->formRow($form->get('senha')); ?>
                        </div>
                    </div>

                </div>
                <div class="panel-footer">
                    <?php echo $this->formRow($form->get('logar')); ?>
                </div>
                <?php echo $this->form()->closeTag($form); ?>
            </div>
        </div>



</div>
<div class="" style="position: fixed; bottom: 0px;width: 100%;">
    <hr>
    <footer>
        <p>&copy; 2005 - <?php echo date('Y') ?> by Zend Technologies Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
    </footer>
</div>
<!-- /container -->
<?php echo $this->inlineScript() ?>
</body>
</html>