<style>
    .radioBotao{

        height: 20px;
        width: 20px;
        display: inline;
    }
    .form-group fieldset label{
        margin-right: 80px !important;
        margin-left: 15px;
    }
    .form-group fieldset{

    }
    .form-group legend{
        font-size: 15px;
        margin-left: 15px;
        /*border-bottom: none;*/
        margin-bottom: 2px;
        font-weight: bold;
    }
</style>
<div class="col-lg-12">
    <div class="panel-primary panel">

        <div class="panel-heading">Cadastro de Funcionário</div>
        <?php echo $this->form()->openTag($form); ?>
        <div class="panel-body">

            <div class="" >
                <div class="form-group">
                    <?php echo $this->formRow($form->get('perfil')); ?>
                </div>
            </div>

            <div class="" >
                <div class="form-group">
                    <?php echo $this->formRow($form->get('nome')); ?>
                </div>
            </div>

            <div class="col-lg-6 row" >
                <div class="form-group">
                    <?php echo $this->formRow($form->get('telefone')); ?>
                </div>
            </div>
            <div class="col-lg-6 row pull-right" >
                <div class="form-group">
                        <?php echo $this->formRow($form->get('email')); ?>

                </div>
            </div>
            <div class="col-lg-6 row" >
                <div class="form-group">
                    <?php echo $this->formRow($form->get('login')); ?>
                </div>
            </div>
            <div class="col-lg-6 pull-right row" >
                <div class="form-group">
                    <?php echo $this->formRow($form->get('senha')); ?>

                </div>
            </div>

        </div>
        <div class="panel-footer">
            <?php echo $this->formRow($form->get('salvar')); ?>
            <!--<button type="submit" class="btn btn-primary">Salvar</button>-->
        </div>
        <?php echo $this->form()->closeTag($form); ?>
    </div>
</div>

<script src="/js/jquery.mask.min.js"></script>
<script>
    (function( $ ) {
        $(function(){
            /* $('.telefone').inputmask({
             mask: '999-99-999-9999-9'
             })*/
            //$('.telefone').mask('(99) 9999 - 9999');
            $('.telefone').focusout(function(){
                var phone, element;
                element = $(this);
                element.unmask();
                phone = element.val().replace(/\D/g, '');
                if(phone.length > 10) {
                    element.mask("(99) 99999-9999",{placeholder:" "});
                } else {
                    element.mask("(99) 9999-99999",{placeholder:" "});
                }
            }).trigger('focusout');
        })
    })(jQuery);
</script>