<div class="col-lg-12">
    <div class="panel-primary panel">

        <div class="panel-heading">Cadastro de Categoria</div>
        <?php echo $this->form()->openTag($form); ?>
        <div class="panel-body">

            <div class="col-lg-12 row" >
                <div class="form-group">
                    <?php echo $this->formRow($form->get('nome')); ?>
                </div>
            </div>

        </div>
        <div class="panel-footer">
            <?php echo $this->formRow($form->get('salvar')); ?>
        </div>
        <?php echo $this->form()->closeTag($form); ?>
    </div>
</div>