

<form method="post" name="gerenciarPermissoes" action="<?php echo $this->basePath();?>/security/permissao/editar/<?php echo $idGrupo; ?>" >
    <?php foreach($list as $module  => $controllersModule): ?>

        <div class="row">
            <h3 style="border-bottom: 1px solid #ddd; "> MODULO - <?php echo $module; ?></h3>



            <?php foreach( $controllersModule as  $controller => $actionsController ): ?>

                <div class="col-md-3">
                    <div class="panel panel-default" style="height: 200px;">
                        <div class="panel-heading">
                            <h3 class="panel-title">CONTROLE - <?php echo $this->rotaRecursoSistema($controller);  ?></h3>
                        </div>
                        <div class="panel-body" style="height: 150px; overflow-y: auto;">
                            <?php foreach($actionsController as $action ): ?>
                                <div class="row col-md-12">
                                    <?php $nameResource = $controller . "\\" . $action; ?>
                                    <input type="checkbox" name="<?php echo  $controller . "\\" . $action; ?>"
                                           value="<?php echo ( array_search($nameResource , $recursos) ) ? array_search($nameResource, $recursos) : $nameResource  ; ?>"
                                        <?php if(  array_search( array_search($nameResource , $recursos), $recursosGrupo) ): ?> checked="checked" <?php endif; ?>
                                        />
                                    <?php echo $action; ?>
                                </div>

                            <?php endforeach; ?>
                        </div>
                    </div>
                </div>
            <?php endforeach; ?>

        </div>


    <?php endforeach; ?>
    <button class="btn btn-primary">Salvar Permissões</button>
</form>

